#!/usr/bin/python3
#	proxmox-tools - Tools to aid management of a Proxmox setup
#	Copyright (C) 2022-2023 Johannes Bauer
#
#	This file is part of proxmox-tools.
#
#	proxmox-tools is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	proxmox-tools is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with proxmox-tools; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys
import re
import ipaddress
from FriendlyArgumentParser import FriendlyArgumentParser
from PVEConfig import PVEConfigs

class ConfigGenerator():
	_CMPKEY_REGEX = re.compile("(?P<prefix>.*?)(?P<no>\d+)")

	def __init__(self, args):
		self._args = args
		self._pveconfig = PVEConfigs()

	def _cmpkey(self, value):
		result = self._CMPKEY_REGEX.fullmatch(value)
		if result is None:
			return (value, 0)
		else:
			result = result.groupdict()
			return (result["prefix"], int(result["no"]))

	def _get_machine_names(self):
		if not self._args.regex:
			with open(self._args.pattern) as f:
				for name in f:
					name = name.rstrip("\r\n")
					yield name
		else:
			names = [ ]
			regex = re.compile(self._args.pattern)
			for name in self._pveconfig:
				if regex.fullmatch(name):
					names.append(name)
			names.sort(key = self._cmpkey)
			yield from names

	def run(self):
		ip = ipaddress.ip_address(self._args.start_ip)
		for name in self._get_machine_names():
			config = self._pveconfig[name]
			print(f"dhcp-host={config.mac},{name},{ip}")
			ip += 1

parser = FriendlyArgumentParser(description = "Create a pseudo-static DNSmasq DHCP configuration from PVE machine name list and a starting IP.")
parser.add_argument("-r", "--regex", action = "store_true", help = "Identify machines by a given regular expression instead of listing them explicitly.")
parser.add_argument("-v", "--verbose", action = "count", default = 0, help = "Increases verbosity. Can be specified multiple times to increase.")
parser.add_argument("pattern", metavar = "filename/regex", help = "Filename that contains machine names to assign IP addresses to or regex to use.")
parser.add_argument("start_ip", metavar = "ip", help = "IP address to assign to the first machine.")
args = parser.parse_args(sys.argv[1:])

cg = ConfigGenerator(args)
cg.run()
